server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MAGAZINE-SERVICE
          uri: lb://MAGAZINE-SERVICE
          predicates:
            - Path=/magazine/**
        - id: PODCAST-SERVICE
          uri: lb://PODCAST-SERVICE
          predicates:
            - Path=/podcast/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost